# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdr < Formula
  desc "Markdown renderer, editor, and linter for the terminal"
  homepage "https://github.com/tirthpatell/mdr"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.0/mdr_0.2.0_macOS_amd64.tar.gz"
      sha256 "78b48d9d8b0ca1856481626d60b4bf00959e230af0e30f3da4172669eb4f3522"

      def install
        bin.install "mdr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.0/mdr_0.2.0_macOS_arm64.tar.gz"
      sha256 "20b10c2073b6f9703e73f0c8b781da86b058eb3dd028c73dd94c912e1b6e1810"

      def install
        bin.install "mdr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.0/mdr_0.2.0_linux_amd64.tar.gz"
      sha256 "14da3fdce2709cfa4846426f593788b4ff4ecf4c6e0b9e4c40a6c09fc2f24d84"
      def install
        bin.install "mdr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.0/mdr_0.2.0_linux_arm64.tar.gz"
      sha256 "1d1761acc358ea13f1d90a6cdcd0fb66f4d9f12e59b01d739769cb1cfdcf492d"
      def install
        bin.install "mdr"
      end
    end
  end

  test do
    system "#{bin}/mdr", "version"
  end
end
