# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdr < Formula
  desc "Markdown renderer, editor, and linter for the terminal"
  homepage "https://github.com/tirthpatell/mdr"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.2/mdr_0.2.2_macOS_amd64.tar.gz"
      sha256 "091af43ef25d3ffe3f82bfe74d07edd8fe995b8a195f9acccdc21fdeeaeb5758"

      define_method(:install) do
        bin.install "mdr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.2/mdr_0.2.2_macOS_arm64.tar.gz"
      sha256 "52a5b8bd7ebe149d0df1563d60db49482fad1009d6c678312061934aa358db1a"

      define_method(:install) do
        bin.install "mdr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.2/mdr_0.2.2_linux_amd64.tar.gz"
      sha256 "bb63b8dc42933bde1cecb931aadbeea9cac9cc8b58bb401131ac8a3a3d9715fd"
      define_method(:install) do
        bin.install "mdr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.2/mdr_0.2.2_linux_arm64.tar.gz"
      sha256 "dfd996c14b580d2f55bbb174805d7105f3b25ec2232b3d05ec7bf986baab96c7"
      define_method(:install) do
        bin.install "mdr"
      end
    end
  end

  test do
    system "#{bin}/mdr", "version"
  end
end
