# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdr < Formula
  desc "Markdown renderer, editor, and linter for the terminal"
  homepage "https://github.com/tirthpatell/mdr"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.1/mdr_0.2.1_macOS_amd64.tar.gz"
      sha256 "cf5cbd90637165329cb1027a3d413bcd67694e40fe3fa7af89d8c719b3300e70"

      define_method(:install) do
        bin.install "mdr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.1/mdr_0.2.1_macOS_arm64.tar.gz"
      sha256 "7b854cf892ce7c777eb4abd83b05e5c9905abe7da83747c1bf8d42ae5aa49ddf"

      define_method(:install) do
        bin.install "mdr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.1/mdr_0.2.1_linux_amd64.tar.gz"
      sha256 "c262083899ec17e9f0cee0e27f55d40c7d060b39406a1e8f379477f08acc8748"
      define_method(:install) do
        bin.install "mdr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tirthpatell/mdr/releases/download/v0.2.1/mdr_0.2.1_linux_arm64.tar.gz"
      sha256 "8acc5c98c13720bfe32ca0787715625b027dc5cebac7ecfc4e6b533ec28bdeb0"
      define_method(:install) do
        bin.install "mdr"
      end
    end
  end

  test do
    system "#{bin}/mdr", "version"
  end
end
